[array1,array2] = meshgrid(-1:0.1:1,-2*pi:0.1:2*pi);
array3 = exp(array1+array2*i);
subplot(3,1,1);
mesh(array1, array2, real(array3));
title('\bf Mesh Plot');
xlabel('\bf x');
ylabel('\bf y');
zlabel('\bf real_z');
subplot(3,1,2);
surf(array1, array2, real(array3));
title('\bf Surf Plot');
xlabel('\bf x');
ylabel('\bf y');
zlabel('\bf real_z');
subplot(3,1,3);
contour(array1, array2, real(array3));
title('\bf Contour Plot');
xlabel('\bf x');
ylabel('\bf y');
zlabel('\bf real_z');